import { StyleSheet } from "react-native";
import { colors } from "./Colors";

// Generated by https://ethercreative.github.io/react-native-shadow-generator/
export const elevations = StyleSheet.create({
  sm: {
    shadowColor: colors.background.dark,
    shadowOffset: {
      width: 0,
      height: 0
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3
  },
  md: {
    shadowColor: colors.background.dark,
    shadowOffset: {
      width: 0,
      height: 0
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8
  }
});
